name: cvision
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  simple_barcode_scanner: ^0.0.8
  http: ^0.13.3
  cloud_firestore: ^4.11.0
  cloud_functions: ^4.5.1
  firebase_auth: ^4.11.1
  modal_progress_hud_nsn: ^0.4.0
  firebase_core: ^2.18.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.5
  rolling_bottom_bar: ^0.2.2
  flutter_spinkit: ^5.2.0
  flutter_animated_button: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
